// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EBNF")>]
[<assembly: AssemblyProductAttribute("YC.Examples")>]
[<assembly: AssemblyDescriptionAttribute("Examples of YaccConstructor usage.")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EBNF"
    let [<Literal>] AssemblyProduct = "YC.Examples"
    let [<Literal>] AssemblyDescription = "Examples of YaccConstructor usage."
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
